name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  APP_NAME: my-app
  JAR_NAME: my-app.jar
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ env.DOCKER_USERNAME }}/${{ env.APP_NAME }}:${{ github.sha }}
        build-args: |
          JAR_FILE=target/${{ env.JAR_NAME }}
    
    - name: Deploy to Kubernetes
      uses: appleboy/kubectl-action@v0.1.4
      with:
        kubeconfig: ${{ secrets.KUBECONFIG }}
        command: apply
        arguments: -f kubernetes.yaml
